name: Docker Image CI

on:
  push:
    branches: [ my_test_portfolio ]
  pull_request:
    branches: [ my_test_portfolio ]

jobs:
  install_requirements:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up python 3.8
          uses: actions/setup-python@v2
          with:
           python-version: 3.8
        - name: Installing packages
          run: |
            python -m pip install --upgrade pip
            pip install -r easycar/requirements.txt
  build_images:
    if: github.ref == 'refs/heads/my_test_portfolio'
    runs-on: ubuntu-latest
    needs: install_requirements
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Add tag
      run: docker tag portfolio docker.pkg.github.com/VsevolodVikhrov/personal_portfolio/portfolio
    - name: Push new image
      run: docker push docker.pkg.github.com/VsevolodVikhrov/personal_portfolio/portfolio
